### ISSUE TITLE
CSS content property gotcha

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#100]
There's a gotcha when using the `::before` pseudo element with the `content` property, because the value needs to itself include quotes:

**Works:**

```ts
$nest:{
    '&::before': {
      content: '"@"'
    },
```

**Does not work:**

```ts
$nest:{
    '&::before': {
      content: '@'
    },
```

It's surprising from the JavaScript API perspective, because you expect that if you pass a string, it'll be handled correctly.

Thoughts?

**Comment by notoriousb1t** [comment]
This was discussed in https://github.com/typestyle/typestyle/issues/30 and CSX subsequently got a quote() helper to try to make this a little easier to read:

http://typestyle.io/#/utilities (toward the bottom of the page).  

There are a lot of valid values for content that would not work correctly if automatically quoted, so I don't know that we can do this without side effects.

https://developer.mozilla.org/en-US/docs/Web/CSS/content

**Comment by basarat** [comment]
> you expect that if you pass a string, it'll be handled correctly.

As from the pointed #30 discussion it needs to match what CSS is going to get written you don't always want it to get quoted magically (example given there `attr`). Personally, I just used backticks since then. 

Having a quick look around other CSS in JS libs don't do special handling either https://github.com/Khan/aphrodite/issues/180 

Just added to docs : http://typestyle.io/#/advanced/-content- :rose:
