### ISSUE TITLE
cssRule allows nested properties statically

### ISSUE THREAD

**Issue by kube** [typestyle/typestyle#108]
This cssRule:

```ts
cssRule('html, body', {
  height: '100%',
  width: '100%',
  $nest: {
    'img': {
      pointerEvents: 'none'
    }
  }
})
```

Is validated by TypeScript but throws an error at runtime:
```
Uncaught TypeError: Registering a CSS rule can not use properties with nested styles(…)
```

**Comment by kube** [comment]
Ok sorry for the bad PR.

I see that you want to allow `$nest` for some special cssRules, like in

```ts
cssRule('@media print', {
  $nest: {
    body: {
      background: 'white'
    }
  }
});
```

But it breaks a little a bit the interest of having static-typing.

**Comment by basarat** [comment]
I am unclear on the exact semantics as well. We just used the hard work done in free-style : https://github.com/blakeembrey/free-style#rules

pinging @blakeembrey for what is and isn't allowed in Rules (I already know `&` isn't allowed) :rose:

![image](https://cloud.githubusercontent.com/assets/874898/22566936/f8a93baa-e9e1-11e6-853d-307e0dd1830b.png)

VS

![image](https://cloud.githubusercontent.com/assets/874898/22566973/1fe1428a-e9e2-11e6-87ee-2fbc8501f13d.png)

Suspicion : If the cssRule key starts with `@` then you are allowed *one* level of selectors, otherwise the key is considered the selector and no nested selectors are allowed.

**Comment by notoriousb1t** [comment]
I'm curious if this is a matter of good practice (and opinion) or if a there is a technical reason for this.

**Comment by kube** [comment]
Maybe Media Queries should be wrapped in a dedicated function, just like `fontFace`?

```ts
media('print', {
  $nest: {
    body: {
      background: 'white'
    }
  }
});
```

**Comment by blakeembrey** [comment]
Rules don't do any interpolation or change the object in any way. It's basically plain CSS as an object. The reason it's not allowed is because it becomes unclear what you're actually trying to do in terms of rule vs selector. See the initial discussion where I disabled it by throwing the error instead of allowing it to cause confusion: https://github.com/blakeembrey/free-style/issues/23.

**Comment by blakeembrey** [comment]
One way to make this easier could be to enable a `registerCSS` function that literally takes an object as CSS. Another (possibly related) solution _may_ be to check for `@`-rules and apply interpolation recursively to the input object - I don't think this one is a huge change.

**Comment by blakeembrey** [comment]
Ok, I got it working in https://github.com/blakeembrey/free-style/pull/50. There's a bit more edge-case handling since no longer a literal object, but overall it's only a like five LOC. Does someone want to review that PR and make sure it doesn't regress anything on this end?

There's one really bad place it can break now that it's not literal. If you put any `@`-rule where the child keys **should not** be interpolated (e.g. keyframes), that will break now. I can't recall if there's anywhere in CSS this is an issue.

**Comment by notoriousb1t** [comment]
I pulled latest free-style with your new code, built it, and ran initial TypeStyle build and tests.  It looks like there are no obvious regressions (even though one test failed, but in a positive way)

The test that failed was:

```ts
 it("transparent string should render transparent in color property", () => {
    reinit();
    cssRule('.transparent', { color: 'transparent' });
    style({ color: 'transparent' });
    assert.equal(getStyles(), '.transparent{color:transparent}.fwarpl0{color:transparent}');
  });
```

And the actual was:
```css
.transparent,.fwarpl0{color:transparent}
```

Which is an improvement!

The keyframes thing can't really be avoided, but it is an edge case that seems outlandish.  I don't think it is anything to worry about.

**Comment by notoriousb1t** [comment]
@kube, TypeStyle has been updated to v1.2.0 to include the newest version of free-style.  Update and you should be good to go!
