### ISSUE TITLE
cssRawPrepend

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#114]
To make it easier to add font faces without having to depend on execution order. 

/cc @notoriousb1t can I get a +1 before I do this :heart: :rose:

**Comment by notoriousb1t** [comment]
Even though I am not a giant fan doing css imports because it always results in a net performance loss, I get the need to facilitate this.  I think that duplicating cssRaw with a slightly different behavior might be confusing.  I think it will raise a common question of which should be used commonly.  My recommendations:

1. Overload ```cssRaw()``` with options ```{ contents: '', behavior: 'prepend' }```
2. Overload ```cssRaw()``` with an additional parameter for prepending```cssRaw(``, true)```
3. Create ```cssImport('https://...', 'https://...', 'https://...')``` that specially handles this edge case.

I am evenly split on these.  1 is the most extensible and effectively discourages this practice. 2 is less hidden but assumes we won't need to extend this function much further.  3 is the most deliberate, but I wouldn't want to encourage people to use ```@import``` if I could help it.

Ultimately, I can't see myself using this feature, so whatever you decide including cssRawPrepend won't ruffle my sensibilities too much.

**Comment by basarat** [comment]
At least chrome is funky with `@font-face` I have found that even if we rewrite the *same* `style` tag even when it has `@font-face` in the start the fonts appear and disappear sometimes. In my work projects we have gone with *two* typestyle instances, one for font faces and one for everything else. A `prepend` will not solve anything for me so closing :rose:
