### ISSUE TITLE
Concept of style sheet

### ISSUE THREAD

**Issue by james-erekson-sportsbet** [typestyle/typestyle#137]
We are in the midst of migrating to Typestyle from CSS Modules/SASS. One thing I noticed straight away was that I want the $debugName on all of my styles, so that it's possible for devs to read the output markup and tell one div apart from another.

So when migrating from SASS, I noticed that my styles would look something like this:

```
const bar = style({
    $debugName: "bar",
    bottom: 0,
    display: "flex",
    position: "fixed"
})

const foo = style({
    $debugName: "foo",
    top: 0,
    width: "inherit"
})
```

And I thought, wouldn't this be better declared as a style-sheet sort of object, similar to CSS modules or JSS?

```
const styles = styleSheet({
  bar: {
    $debugName: "bar",
    bottom: 0,
    display: "flex",
    position: "fixed"
  },
  foo: {
    $debugName: "foo",
    top: 0,
    width: "inherit"
  }
})
```

And then even better if this styleSheet function could automatically pass in the $debugName as the key you assigned it to?

So I've already implemented this styleSheet function. Would you have any interest in allowing this kind of construct in the Typestyle library? I can try to put together a pull request if you are interested.

**Comment by notoriousb1t** [comment]
How would "styles"  be used in that example above?  It sounds like you are saying:


```ts
const styles = styleSheet({
  bar: { 
    bottom: 0,
    display: "flex",
    position: "fixed"
  },
  foo: { 
    top: 0,
    width: "inherit"
  }
});

<div className={styles.bar}></div>
```
(styles.bar would automatically have $debugName to bar)

How would this function when bar has nested styles?

**Comment by TylorS** [comment]
I believe this behavior can be emulated, minus the debugName, with either `namespace`

```typescript
namespace styles {
  export const foo = style({ ... })

  export const bar = style({ ... })
}

<div className={styles.bar}></div>
```
or with using a separate file for your styles

```typescript
// styles.ts
export const foo = style({ ... })

export const bar = style({ ... }) 

// view.ts
import * as styles from './styles'

<div className={styles.bar}></div>
```

I tend to prefer the latter.

**Comment by james-erekson-sportsbet** [comment]
@notoriousb1t That's exactly how I imagine using it. As far as nested styles, it needn't be any different from how the nested styles work now. So:

```
const bar = style({
    $debugName: "bar",
    color: "red",
    $nest: {
        "&:hover": {
            color: "blue"
        }
    }
});

<div className={bar}></div>
```
would be equivalent to:
```
const styles = styleSheet({
    bar: {
        color: "red",
        $nest: {
            "&:hover": {
                 color: "blue"
            }
        }
    }
})

<div className={styles.bar}></div>
```
Then in both cases the output div looks something like:
```
<div class="bar_fnerj9u"></div>
```

@TylorS both of those options look good for the concept of the style sheet, but I guess (at least in the first instance) my reason for using it is so that we can get the $debugName mixed in automatically as the key name. Whereas in both of those examples, when we call style({...}) we'll have to manually pass the $debugName.

**Comment by basarat** [comment]
-1 from me. Reasons:

* More code
* Can be done in user code. 
* `bar` / `foo` are local variables in a file. You might want your debug name to be more explanatory
* Not a big fan of debug name (personally). I prefer to debug dom instead of styles e.g. `<div data-comment="foo" className={fooClass}/>`
* The return type of `styleSheet` is unsafe https://github.com/typestyle/typestyle/pull/138/files#diff-77e481176c7f4c33ca55b5b2ae2f9c78R215 https://github.com/typestyle/typestyle/pull/138/files#diff-41df78d86ed4de80aae9b0b9560feb2bR2563 You can do `foo = styleSheet({red: {...}})` and then `foo.rad`(typo) without erroring. TypeScript latest mapped types can help here ... but that brings me to the biggest reason
* The biggest reason is of course not adding any more things we need to document / users need to read :) 

@james-erekson-sportsbet also 👋 :heart: :rose:
