### ISSUE TITLE
Overriding CSS properties

### ISSUE THREAD

**Issue by Frikki** [typestyle/typestyle#139]
I’ve encountered a peculiar issue.

```
const myStyle = style({
  backgroundColor: 'red',
  background: 'blue',
})
```

In ordinary CSS, `background` would override `background-color`. However, this is not the case with TypeStyle. I consider this to be a bug. :heart:

**Comment by notoriousb1t** [comment]
background and background-color are treated equally by CSS.  Neither the shorthand nor longhand form have precedence.

http://codepen.io/notoriousb1t/pen/46414faf8a232e9496d4ed9986872517/

**Comment by notoriousb1t** [comment]
I should elaborate here...

As part of the de-duplication process and hashing, the property keys are ordered alphabetically.  Since CSS does not treat one property over another and shorthand properties generally come first alphabetically, the longhand properties will be taken over the shorthand properties in TypeStyle.  I believe we have this written up somewhere, but I can't find it at this moment.

If you think about it though, if you are using both shorthand and longhand properties, the longhand properties are more specific, that is more detail than the shorthand properties, so I think this is pretty intuitive.

**Comment by basarat** [comment]
We've known this for a while. Similar issues exist for padding / margin etc and hence helpers exist in css tips :heart:

To add here http://typestyle.io/#/advanced / https://github.com/typestyle/typestyle.github.io/blob/source/src/docs/advanced.md :rose:

# Ordering property names 
Because we use JavaScript objects for style properties, the key order is not guaranteed. So before we generate the CSS we order them alphabetically. You should not mix and match short hand property names with the longhand form e.g. the following object 

```js
{
  backgroundColor: 'red',
  background: 'blue',
}
```
Will generate the CSS: 
```css
background: blue;
backgroundColor: red; 
```
Resulting in a `red` color.

**Comment by basarat** [comment]
Similar behaviour exist in other CSS in JS libs that use js objects. TypeStyle / FreeStyle is not unique in this case and FreeStyle sorting by key names is the behaviour followed by other libs too :rose:

**Comment by Frikki** [comment]
Thank you :heart:

**Comment by basarat** [comment]
Reopening just to add to docs 🌹

**Comment by Frikki** [comment]
This behavior actually means that we should for all in the world avoid using shorthand properties.
