### ISSUE TITLE
What packages and what text editor does Basarat use in their Egghead series?

### ISSUE THREAD

**Issue by daniphilia** [typestyle/typestyle#154]
👍

**Comment by basarat** [comment]
Free and open source : http://alm.tools/ Designed specifically so that my TypeScript demos work reliably 100% of the time. Few things that need to be done for such reliability: 

* 100% Reliable deterministic error analysis https://alm-tools.gitbooks.io/alm/content/features/errors.html 
* Syntax highlighting *using the compiler API* https://alm-tools.gitbooks.io/alm/content/features/typescript.html#syntax-highlighting 

etc :rose:

Sadly not designed for 1GB monorepos but I personally don't work on projects with such code bases at the moment either :heart:

**Comment by daniphilia** [comment]
d

**Comment by notoriousb1t** [comment]
(It also has a pretty sweet test runner that lets you see the results of your tests side by side with the test code)

**Comment by basarat** [comment]
> What were the go-to word addons and the omnisearch addons? Are those features of Alm?

Yes all built in : https://alm-tools.gitbooks.io/alm/content/features/omni-search.html :rose:
