### ISSUE TITLE
Automatic vendor prefixing

### ISSUE THREAD

**Issue by PFight** [typestyle/typestyle#186]
Nice library, but without prefixing is not usable...

**Comment by notoriousb1t** [comment]
I'm sorry that this does not work out of the box for your environments.  However, browser vendors have done away with adding vendor prefixes for new features and instead use config flags to turn features on or off.  Even Internet Explorer 11 does not use the -ms prefix according to their documentation.  For developers supporting modern browsers, vendor prefixing is no longer necessary in most cases.  It is the exception rather than the rule.

If you are in a position where you need to specify browser prefixes, you can accomplish in at least two ways:

**specify the vendor prefixes as necessary in the style definitions**
```ts
const flexRow = style({ 
     display: [ '-ms-flex-box', 'flex' ]
})
```

If 

**wrap the style function in an auto-prefixer of your own**
```ts
import { style } from 'typestyle'

function prefix(props: NestedCSSProperties) {
     const result = {} as NestedCSSProperties
     for (const prop in props) {
         if (prop === '$nest') {
              const nested = {} as NestedCSSSelectors
              for (const selector in props.$nest) {
                  nested[selector] = prefix(props.$nest[selector])
              }
              result.$nest = nested
              continue;
         }
         // detect and prefix properties here
         // make sure to assign standard property name last
    }
    return result
}

export function autoStyle(props: NestedCSSProperties) { 
    return prefix(props)
}
```

We decided a while back not to add this or to add middleware to keep TypeStyle simple and small in size.  If you are using this for flex specifically, the csstips library has vendor prefixes already built in.
