### ISSUE TITLE
Is there a recommended way of debugging?

### ISSUE THREAD

**Issue by minnam** [typestyle/typestyle#263]
Pardon me if this is not a place to ask questions. As my code grows, it's getting difficult to debug styling coming from using browser inspector to debug my CSS. Am I not understanding the purpose of the library or do you guys have a practice or a way of debugging css instead of relying on browser inspector?

**Comment by notoriousb1t** [comment]
I typically use https://typestyle.github.io/#/core/stylesheet because it automatically adds a class prefix.
  
Prior to that being added, I would add $debugName (the class prefix) to the style definition as needed so I could easily find which rule I am debugging.  The downside of using $debugName is that it disables the de-duplication feature, but I am in a situation where the maintainability of having $debugName is more important than the reduction and collapsing of CSS rules.

Both of those methods still use the browser inspector.

**Comment by minnam** [comment]
Thank you @notoriousb1t for letting me know, it's very helpful
