### ISSUE TITLE
Definition of css variables.

### ISSUE THREAD

**Issue by Johnz86** [typestyle/typestyle#272]
I want to use and modify css variables on the fly. The only example of this I found here: 

https://typestyle.github.io/play/#src=cssRule(':root',%20%7B%0A%20%20'--primary-color':%20'red'%20%20%0A%7D);%0A%0Aconst%20myClass%20=%20style(%7B%0A%20%20color:%20'var(--primary-color)'%0A%7D);%0A%0A%3Cdiv%20className=%7BmyClass%7D%3E%0A%20%20Hello%20world%0A%3C/div%3E

The problem is that cssRule will throw an error in typescript for NestedCSSProperties.

How do I properly define css variables and modify them with typestyle?

**Comment by basarat** [comment]
You can use cssRaw : https://typestyle.github.io/#/raw/cssraw

**Comment by notoriousb1t** [comment]
In general it is not a great idea to rapidly change styles at :root.  The most performant way to deal with custom css properties is to set them at the lowest level in the DOM as possible since css custom properties also cascade. (possibly causing unnecessary reflows and repaints)

I would recommend getting a ref to a top level element in your component and setting them with ref.current.style.setProperty() on mount().

**Comment by Johnz86** [comment]
There are use cases, when this is desired. 
For example I have flexbox table with columns, that are resized via css variables. I do not need to this often and reflows are invisible to the eye. This gives more performance, when this action is decoupled from component just tied to css class. 
I want to retain the applied variable values. So I do not need to store the sizes of columns in redux.
When the component is unmounted and mounted again previously applied values are still there.
This is very lightweight solution, which I desire.

**Comment by Frikki** [comment]
@notoriousb1t 

> The most performant way ...

What does “performant” mean? Oxford dictionary says it means _functioning well or as expected_, while Cambridge says it means _working in an efficient way_. I have heard people say it also means fast, but fast to whom? Merriam-Webster doesn’t list the word, and neither does dictionary.com.

Technopedia has this to say about “performant”:

> Performant means that something is working correctly or well enough to be considered functional. In a technology context, this term is believed to have originated with programmers seeking a concise word to express that a system or program will work, but may not yet be optimal. Performant may have come from a portmanteau of performance and conformant - as in working and meeting existing standards.
>
> Performant has become a business buzzword in addition to being programmer slang. Essentially, performant is a fancier way of saying that a program or system is acceptable. Depending on the context, this could mean good enough to package and sell, or simply good enough to elevate to the next level of testing. In some contexts, performant may mean a product is as good as it can be while remaining cost-effective, and that any additional time spent on it will push development costs beyond the budget.

So, what does it mean?

**Comment by notoriousb1t** [comment]
@Frikki what I meant to say is it will yield optimal performance in the largest amount of typical cases.  Setting a css variable at root is similar to setting the font-size at root.  It can affect the whole document, so you should do so with care.  To compound that, CSS doesn't know what type of information is in the CSS variable.  They are effectively untyped until they are used in a rule, so that may force reflows/repaints in situations that might not otherwise require it.

@Johnz86 If you are really trying to set a global, I would recommend using 

```ts
document.body.style.setProperty("--my-var", "value");
```
It is effectively same as doing a root selector in CSS and will fix your immediate issue of root repeating itself.

Example: https://codesandbox.io/s/303p9818x6

**Comment by notoriousb1t** [comment]
Closing, continuing this in #273
