### ISSUE TITLE
How to use media() in stylesheet?

### ISSUE THREAD

**Issue by trusktr** [typestyle/typestyle#286]
The docs show using `media` in a `style()` call, but what about in an `stylesheet()` call?

**Comment by trusktr** [comment]
Oops, I was using `$nested` instead of `$nest`, but `$nest` is still [not working](https://typestyle.github.io/play/#src=const%20css%20=%20stylesheet(%7B%0A%20%20foo:%20%7B%0A%20%20%20%20fontSize:%2032,%0A%20%20%20%20color:%20'darkcyan',%0A%20%20%20%20%0A%20%20%20%20$nest:%20%7B%20'&%20div':%20%7B%0A%20%20%20%20%20%20color:%20'red'%0A%20%20%20%20%7D%7D,%0A%20%20%7D%0A%7D);%0A%0A%3Cdiv%20className=%7Bcss.foo%7D%3E%0A%20%20Hello%0A%20%20%3Cdiv%3E%20world%3C/div%3E%0A%3C/div%3E).

**Comment by trusktr** [comment]
Alright, it worked, but guess what: I had to refresh the page!

**Comment by trusktr** [comment]
Sweeet, it works with `media()`. It may be worth adding [such example](https://typestyle.github.io/play/#src=const%20css%20=%20stylesheet(%7B%0A%20%20foo:%20%7B%0A%20%20%20%20fontSize:%2032,%0A%20%20%20%20color:%20'darkcyan',%0A%0A%20%20%20%20$nest:%20%7B%20'&%20.bar':%20%7B%0A%20%20%20%20%20%20background:%20'red',%0A%20%20%20%20%20%20...media(%7BminWidth:%201024%7D,%20%7B%0A%20%20%20%20%20%20%20%20background:%20'pink',%0A%20%20%20%20%20%20%7D),%0A%20%20%20%20%7D%7D,%0A%20%20%7D%0A%7D);%0A%0A%3Cdiv%20className=%7Bcss.foo%7D%3E%0A%20%20Hello%0A%20%20%3Cdiv%20className=%22bar%22%3E%20world%3C/div%3E%0A%3C/div%3E) to docs.

**Comment by ratiofu** [comment]
It took me a moment to make it work with _using multiple_ `@media` declarations in the same `stylesheet` section. Perhaps the following can save the next person some time ... or it can be added to the documentation ... or a simplified helper for this be part of the API? Is there a simpler way to accomplish this?

`media(...)` returns a `NestedCSSProperties` object that _contains a single `$nest` key_ with the value being the object representation of the media query. So in order to use multiple such rules together, they need to be merged via `extend` and then decomposed. If you _also_ want to use `$nest` in the same block, you have to put it _inside_ the `extend` call, like so:

```typescript
export const css = stylesheet({
  pageGrid: {
    // ...
    display: 'grid',
    gridTemplateRows: 'auto 1fr auto',
    ...extend(
      {
        $nest: {
          '&>*': {
            outline: '2px solid orange' // just for testing purposes
          }
        }
      },
      media(
        { minWidth: 0, maxWidth: 600 },
        { width: percent(100) }
      ),
      media(
        { minWidth: 601, maxWidth: 960 },
        { width: px(600) }
      ),
      media(
        { minWidth: 961 },
        { width: px(960) }
      )
    )
  },
  // ...
```

**Comment by dlants** [comment]
@ratiofu thanks for the explanation, that saved me a ton of time. Agree that the docs could be clearer about how the media query works, since it's really natural to write:

```
stylesheet({
  ...media(...), // does not work, since the next media will overwrite the $nest key
  ...media(...)
```
