### ISSUE TITLE
Adding typestyle to project affects the compilation tree

### ISSUE THREAD

**Issue by tomitrescak** [typestyle/typestyle#34]
Hi. Thanks for the fantastic project.
I have a problem that I have no idea why is happening.
When I have no typestyle in my project files compile to the specified directory.
When I add typestyle into the project and import it into any file, the project starts to compile into subdirectory "src".

Original:
Source files in "src/client", "src/server"
Compiled
"dist/client" ...

With typestyle
Compiled
"dist/src/client"

I can post you a gif if needed.

**Comment by basarat** [comment]
This should not happen. However this is not the first weird issue to result from our choice of using `.ts` instead of `.d.ts` + `.js` in a lib directory and has pushed / convinced me to reconsider how we are building this project.

I suspect I will have the change the location of `csx` so that all the src is in `src` (both typestyle and csx) and all the output is in `lib`, so we will have `typestyle/lib/csx` for csx stuff and user will need to `import * as csx from "typestyle/lib/csx"`

I'm about to go on a 24 hour flight. Will post a PR afterwords :heart: :rose: /cc @notoriousb1t

**Comment by basarat** [comment]
Note: the name `lib` is becoming conventional for even pure ES6 transpiled projects e.g. https://github.com/FormidableLabs/react-animations#usage

```
import fadeIn from 'react-animations/lib/fade-in'
```

**Comment by notoriousb1t** [comment]
That sounds like a good plan.  I don't have any outstanding work out on the csx so now is a good time from my perspective.

**Comment by basarat** [comment]
# Further notes

Key reasons for doing this change 

* doesn't work with tsloader right now (this can be fixed)
* confuses `outDir` option for nodejs users 
* forces us to use the strictest ts features. This is okay but as new features come out we don't want people waiting on us to support them. 

Things to do:

* [ ] Update website
* [ ] Update readme 
* [ ] Add to release notes

**Comment by basarat** [comment]
All done https://github.com/typestyle/typestyle/releases/tag/v0.7.0 Enjoy :rose:
