### ISSUE TITLE
line-height does not transpile right

### ISSUE THREAD

**Issue by ericgoe** [typestyle/typestyle#360]
Hey,

First of all, I want to thank all the collaborators for such an awesome package !
Thank you.

I might just encountered a bug. I have the following code.
```
import { style } from 'typestyle'

const styles = style({
    height: 50,
    lineHeight: 50,
})
```
### Expected behaviour

a class with following properties
```
{
    height: 50px;
    line-height: 50px;
}
```
### Actual behaviour

a class with following properties
```
{
    height: 50px;
    line-height: 50;
}
```

The browser (f.e. Chrome) cannot interpret the value of `line-height` because 'px' is missing and sets the line-height to 0px.

**Comment by basarat** [comment]
We actually don't do any unit interpretation. The value you pass is what gets put in the CSS stylesheet transparently, so you get the standardised CSS behaviour (instead of some custom one that you will have to learn). In CSS (and therefore typestyle) my recommendation to always put units, unless the value is 0 :rose:

Now on to CSS: 
- LineHeight unitless is considered a multiplier: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height 
- Height unitless is considered px 

Chrome is just showing you the css interpreted value.
