### ISSUE TITLE
Nested classes

### ISSUE THREAD

**Issue by tomitrescak** [typestyle/typestyle#4]
@basarat, once again, kudos! One question though. Can we do nested classes?

**Comment by basarat** [comment]
> Can we do nested classes?

Don't need them. Simply create the classes you need and then use them:

```tsx
namespace ButtonStyles {
   export const root = style({color:'red'});
   export const text = style({'fontWeight':'bold'});
}
const Button = ({text})
  => 
    <button className={ButtonStyles.root}>
      <div className={ButtonStyles.text}>{text}</div>
    </button>
```

Hope that helps :rose:

**Comment by Frikki** [comment]
However, when dealing with components, there are often times where I want a descendant component to be styled differently in various ancestors. As this isn’t particularly difficult, issues arise when two different parent components share the same hash, because of their equal styles. 

To my knowledge, I then have to use `cssrule` with a unique component CSS class name and then nest imported descendant component CSS classes.

I’d appreciate if you could shine a little light on this issue, @basarat .

Many thanks! :rose:

**Comment by basarat** [comment]
> There are often times where I want a descendant component to be styled differently in various ancestors

One possible solution: You can make the child take a `className` prop and pass in different values from different parents :rose:

**Comment by apexskier** [comment]
Workaround shown here: https://github.com/typestyle/typestyle/issues/175#issue-249670827

**Comment by Frikki** [comment]
@apexskier I don’t see any workaround shown.

**Comment by fi5u** [comment]
I'm trying to understand the solution to this problem. I have a wrapper div with a button contained as a child x levels deep. When the the wrapper div is hovered I want to style the button differently. Currently I'm attaching a `data` property to the button, so I can reference it from `$nest`. For example:

```
const button = style({
  borderColor: 'green',
})
const wrapperDiv = style({
  '$nest': {
    '&:hover [data-name="btn"]': {
      borderColor: 'red',
    },
  }
})
```

Ideally, I'd be able to reference the `button` generated class name from  within the `wrapperDiv`'s `$nest`. @basarat I don't understand how the solution above could work in this situation. Apologies if I'm missing something obvious here.

**Comment by bradleyayers** [comment]
@fi5u do something like this:

```
const button = style({
  borderColor: 'green',
})
const wrapperDiv = style({
  '$nest': {
    [`&:hover .${button}`]: {
      borderColor: 'red',
    },
  }
})
```

**Comment by fi5u** [comment]
@bradleyayers Brilliant, thanks!

**Comment by notoriousb1t** [comment]
The reason I would caution against that method is that it is possible to unintentionally add this hover behavior to a parent with the same css property + value.  You can bandaid that by using an $debugName because that changes the resulting hash.

I think in this situation it would be safer to use data attributes or the tagName if possible.

**Comment by bradleyayers** [comment]
@notoriousb1t thats a great point!

**Comment by trusktr** [comment]
> The reason I would caution against that method is that it is possible to unintentionally add this hover behavior to a parent with the same css property + value. You can bandaid that by using an $debugName because that changes the resulting hash.
> 
> I think in this situation it would be safer to use data attributes or the tagName if possible.

Dang, that's a hassle. I would like if typestyle has an official way of doing this without caveats.

**Comment by trusktr** [comment]
As @notoriousb1t said, this will not create unique class names per component, which means it isn't possible to create style scoping using the `const foo = style()` trick.

I've given an example of how JSS does it here: https://github.com/typestyle/typestyle/issues/175#issuecomment-420180505
