### ISSUE TITLE
Towards greater safety

### ISSUE THREAD

**Issue by basarat** [typestyle/typestyle#40]
The following *could* error (TypeScipt freshness https://basarat.gitbooks.io/typescript/content/docs/types/freshness.html) but doesn't http://typestyle.io/play/#src=style(%7B%0A%20%20colour:'red'%0A%7D)

```ts
style({
  colour:'red' // typo
})
```

The reason is our string indexers e.g. `[propertyName: string]: any;` in `CSSProperties`. These ensure we work with interpolation / media queries. We *could* make custom functions that take `CSSProperties` and *internally* lie to the compiler e.g. a `media` function  can be: 

```ts
export const media = (mediaQuery: string, ...objects: CSSProperties[]): CSSProperties => {
  const object = { [stringMediaQuery]: extend(...objects) };
  return object as any;
}
```
And you would use it like: 

```ts
const sizeChangingClass = style(
  {transition: 'font-size .2s'},
  media(`@media (min-width: 0px) and (max-width: 600px)`, {fontSize: '24px'})
);
```
A similar function could be `interpolate` (same body actually).

With the name *Type*Style I feel like its injustice to allow errors like this to go unchecked. 

/cc @notoriousb1t @blakeembrey @staltz would love your thoughts :rose:

**Comment by notoriousb1t** [comment]
Totally agree with you on making the typings stricter.

I think there is a way to make this work without creating a secondary function.  Instead of extending CSSProperties into NestedCSSProperties, we could create a type for CSS Properties (CSSPropertyMap) which has the CSS properties in it, a second type for CSS nesting called NestedCSSProperties which has [selector: string]: CSSProperties | undefined; to restrict them properly, and then a third type (CSSProperties) which is a union of CSSPropertyMap and NestedCSSProperties.  

I am creating a branch to see how this would work.

**Comment by notoriousb1t** [comment]
@basarat unfortunately, I can't think of a way to make this more type safe without making a few breaking changes to the code.  The reason is:

```typescript
type NoCompile = {
  length: number;
  [key: string]: string;
};
```

We simply can't share a type containing selectors and properties and expect the TypeScript compiler to be able to catch { colour: 'red' }.  

To remedy this, I think we should create a property named nested (name TBD) that will allow for nesting selectors, pseudo-selectors, media queries, etc.

```ts
const redClass = style({ 
  color: red,
  nested: {
     '&:hover': {
        color: red.darken(.2)
     }
  }
});
```

To make it easier for pseudo-selectors (or other really common cases, we can create shorthands properties:

```ts
const redClass = style({ 
  color: red,
  '&:hover': {
    color: red.darken(.2)
  }
});
```

We might have to tweak to make media queries easier.  I am not 100% if we would add a property called (at)media as an array of media objects or what.

I have gone through and made these changes on a branch, so I could work through that stuff.  As a result, I had to add quite a few things to css.d.ts.  It turns out we had tests and helpers that weren't able to compile since their properties were not in css.d.ts.  Your concern is well founded.

Here is the branch: https://github.com/typestyle/typestyle/tree/css-props-experiement.  If we proceed in this direction, I can create a PR so we can work through other issues.

**Comment by basarat** [comment]
> Your concern is well founded.

Many of them are actually my problems e.g. I knew the vendor prefixed flexbox names were not in `CSSProperties` and that I would need to add them in, I just chose to delay that till we had the other stuff we've done ready. So good job :rose: :heart: 

Instead of 

```ts
const redClass = style({ 
  color: red,
  nested: {
     '&:hover': {
        color: red.darken(.2)
     }
  }
});
```
I'm essentially suggesting: 

```ts
const redClass = style({ 
  color: red,
  nested('&:hover', {
     color: red.darken(.2)
  })
});
```

Reason: Because adding a `nested` property will essentially need to have the same `{[key:string]:Something}` signature which kills off TypeScript's strict object checking. With the `nested` function the string key is done *once*. Also its easier to manage imho as its an explicit call by the user which we can handle at a targetted location, instead of an implicit object property we need to special case.

**Comment by notoriousb1t** [comment]
Hmm... I can't think of a way to make that syntactically sound 🙁 

The selector under nested would only be checked as a string; however, the properties of each of those selectors would be type safe

```ts
type CSSProperties = CSSPropertyMap & NestedCSSProperties;

type CSSPropertyMap = {
  '-webkit-overflow-scrolling'?: string;

  /* other CSS Properties */

  zoom?: "auto" | number;
}

type NestedCSSProperties = {
  '&:active'?: CSSProperties;

  /* other pseudo-selectors */

  '&:visited'?: CSSProperties;
  nested?: NestedCSSSelectors;
}

type NestedCSSSelectors = {
  [selector: string]: CSSProperties | undefined;
};
```

In other words, this would be uncompilable because of the property "colour" and not based on the @media screen atRule:

```ts
style({
  nested: {
    '@media screen': {
        colour: 'red'
     }
  }
})
```

**Comment by basarat** [comment]
@notoriousb1t Sorry for the delay. Thinking about it more I am happy with what you are suggesting (a special `nested` sub property). It actually doesn't lie to the type system and you don't need to *import* another thing from `"typestyle"`. Thanks for your brilliance once again :rose: :heart:

**Comment by blakeembrey** [comment]
Some ways to do it:

**Array DSL (using `Object.assign`):**

```ts
style([
  style.color('red'),
  { mozFallbackThing: 'test' }
])
```

**Chaining DSL:**

```ts
style.color('red').css({ mozFallbackThing: 'test' })
```

**Object spread:**

```ts
style({
  ...style.color('red'),
  mozFallbackThing: 'test'
})
```

Using the array seems nicest as you can easily mix arrays down the chain when using nested helpers. However, there's the small overhead of all the object creation and merging.

```ts
style([
  style.color('red'),
  style.at.media('(min-width: 600px)', [
    style.color('blue'),
    { mozFallbackThing: 'test' }
  ])
])
```

**Comment by basarat** [comment]
This has been done. Website / docs have been updated. Further tracking done here https://github.com/typestyle/typestyle/issues/43 :rose:
