### ISSUE TITLE
Object literal may only specify known properties, and ''-webkit-font-smoothing'' does not exist in type 'NestedCSSProperties'.

### ISSUE THREAD

**Issue by khkmzynv** [typestyle/typestyle#52]
After update to 0.14. So how can I use -webkit- properties, not pseudos.

**Comment by Hapet95** [comment]
and also for fontface
![image](https://cloud.githubusercontent.com/assets/20340782/20925050/fd3acde2-bbcd-11e6-8531-62d7c26dca7e.png)

**Comment by notoriousb1t** [comment]
@Hapet95 Try out fontFace

```ts
import {fontFace} from 'typestyle';

fontFace({
    fontFamily: 'Lato'
});
```

**Comment by notoriousb1t** [comment]
also, which -webkit properties are missing that you noticed?  Updating the type declarations is a pretty fast thing to fix.

**Comment by notoriousb1t** [comment]
Added the majority of vendor prefixes in 0.14.3.  That includes -webkit-font-smoothing. 😄

**Comment by Hapet95** [comment]
Thanks! But I've found a few mistakes as well and have fixed them in this pull request ;)
https://github.com/typestyle/typestyle/pull/55

**Comment by chinanderm** [comment]
Was ''-webkit-font-smoothing" removed?

**Comment by basarat** [comment]
# Verified 

This project no longer has its own css type definitions, instead it leverages the community shared `csstype` : https://github.com/typestyle/typestyle/blob/c1d4db1e68d3e3405a79728308930ceb4848db0c/package.json#L30 Mentioning that its an issue thats going to impact others as well :rose:

**Comment by basarat** [comment]
# Workaround
Declare it as an augmentation in your project: https://typestyle.github.io/#/core/tip-declaring-new-css-stuff

# Why its broken
It is not in the file : https://raw.githubusercontent.com/frenic/csstype/master/index.d.ts

Because its not listed in mdn : https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust 😢 

# Halp Please
Create an issue here : https://github.com/frenic/csstype/issues (and mention this one)
And create an issue here : https://github.com/mdn/data/issues (and mention the one your created in csstype)

Reference example of the kind of issue:
https://github.com/frenic/csstype/issues/58
https://github.com/mdn/data/issues/316

Thanks :rose:
