### ISSUE TITLE
Treelike writing of pseudo and children of elements is broken

### ISSUE THREAD

**Issue by Hapet95** [typestyle/typestyle#56]
One of the things that I like in the TypeStyle is treelike writing of pseudo and children of elements. but now this feature is broken :/

![image](https://cloud.githubusercontent.com/assets/20340782/20961457/85223e1a-bc7e-11e6-9423-9bbbaf5644a5.png)

**Comment by jamiewinder** [comment]
I've just encountered this myself. I was under the impression that `$nest` needed to be specified at all levels. I do this in my code, though this is also now broken (but worked fine before).

**Comment by notoriousb1t** [comment]
As @jamiewinder mentioned, The type definitions to support multiple nested layers in 0.14.5 😃 

Here is a working example
```ts
const randomClass = style({
  color: 'red',
  $nest: {
    span: {
      color: 'darkred',
      $nest: {
        '&:hover': {
          borderBottom: 'solid thin black'
        }
      }
    }
  }
});

<div className={randomClass}>
  <span>
    Hover
  </span>
</div>
```


http://typestyle.io/play/#src=const%20randomClass%20=%20style(%7B%0A%20%20color:%20'red',%0A%20%20$nest:%20%7B%0A%20%20%20%20span:%20%7B%0A%20%20%20%20%20%20color:%20'darkred',%0A%20%20%20%20%20%20$nest:%20%7B%0A%20%20%20%20%20%20%20%20'&:hover':%20%7B%0A%20%20%20%20%20%20%20%20%20%20borderBottom:%20'solid%20thin%20black'%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D);%0A%0A%3Cdiv%20className=%7BrandomClass%7D%3E%0A%20%20%3Cspan%3E%0A%20%20%20%20Hover%0A%20%20%3C/span%3E%0A%3C/div%3E

**Comment by Hapet95** [comment]
Don't you think, that it slightly increases the code? :) How it is justified?

**Comment by notoriousb1t** [comment]
I wish that we could nest selectors along with css properties 😦 .  

Unfortunately, TypeScript does not allow the following example:

```ts
type noCompile = {
    color: string;
    [selector: string]: NestedCSSProperties;
};
```

We can't narrow the string indexer down to NestedCSSProperties, because color's type of string doesn't adhere to that interface.  In effect, there was not a whole lot of compile time checking before because selectors had a type of any due to that restriction.

We started to discuss going in this direction in this issue:
https://github.com/typestyle/typestyle/issues/40

And if you look around Nov 28, there was some discussion on the Gitter channel
https://gitter.im/typestyle/general

But yes, it would be nicer if the other syntax was type checkable.
