### ISSUE TITLE
colorHelpers.toString() very long float number output

### ISSUE THREAD

**Issue by Hapet95** [typestyle/typestyle#58]
Sometimes ColorHelper.toString() starts outputing very long float numbers in rgba().

![image](https://cloud.githubusercontent.com/assets/20340782/20990618/22d4b8ee-bcf3-11e6-90f4-3a9c292d4fae.png)

**Comment by basarat** [comment]
Note: This is just JavaScript number math. e.g. `.1 + .2` you get `0.30000000000000004`. 
Leaving open for analysis / decision by Christopher :rose:

**Comment by Hapet95** [comment]
maybe use .toFixed(1) ?

**Comment by notoriousb1t** [comment]
@basarat  is correct, JavaScript represents approximations of floating point numbers which sometimes end up with a very tiny trailing number right of the decimal.  I thought I had taken measures to counter this by rounding to the nearest 3/5 position, but it looks like your environment is not converting these to integers.

Does anyone know if a decimal place in RGB and HSL is meaningful?  I suspect it is not since conversions to hex would naturally round the number.  If that is the case, we can round to the nearest whole number for RGB and H channels.

**Comment by Hapet95** [comment]
I think you are right. For RGB definitely not. Only for RGBA's alpha 😃

**Comment by notoriousb1t** [comment]
I fixed this to round RGB and H in https://github.com/typestyle/csx/commit/c675a4d08db9a32c33381cca4891d07d2d2a135f

We split up the typestyle package into 3 packages in preparation for version 1.0.0 of typestyle.  To get these latest changes, you will need to upgrade to typestyle 0.8.12 and npm install csx 8.0.3.
