### ISSUE TITLE
Providing ES2015 builds

### ISSUE THREAD

**Issue by TylorS** [typestyle/typestyle#69]
Hello, first off thank you for the wonderful work here. I've been enjoying this library immensely. 

Recently I've been trying to update all of my dependencies to provide ES2015 builds and TypeStyle remains one of the last of them which are commonjs only.

I'd love to create a PR, but didn't want to do so without getting feedback on if it would be accepted. Typically I've created 2 separate tsconfigs, `tsconfig-es2015.json` and the "standard" `tsconfig.json` looking something like these

```typescript
// tsconfig.json
{
  "compilerOptions": {
    ...,
    "module": "commonjs",
    "target": "es5",
    "outDir": "lib/commonjs"
  },
}

// tsconfig-es2015.json
{
  "compilerOptions": {
    ...,
    "module": "es2015",
    "target": "es5",
    "outDir": "lib/es2015"
  },
}
```

Then in the libraries `package.json` changing or adding the following fields

```typescript
{
  "main": "lib/commonjs/index.js",
  "module": "lib/es2015/index.js",
  "jsnext:main": "lib/es2015/index.js",
  "typings": "lib/es2015/index.d.ts" // could just as well be lib/commonjs/index.d.ts
}
```

Thanks for your time!

**Comment by basarat** [comment]
> Hello, first off thank you for the wonderful work here. I've been enjoying this library immensely.

Thank *you* :rose: :heart:

> TypeStyle remains one of the last of them which are commonjs only.

I doubt this to be the case, e.g. you must be depending upon something like vue or react or angular and they would be providing es5 only builds. Perhaps I am out of date and would love to be told that I am wrong :heart:

My only concern is that it makes path based imports harder `import {something} from "typestyle/lib/es2015/something"` :rose:

**Comment by Frikki** [comment]
@basarat You’re out of date ;) We are using Cycle.js or rather Motorcycle.js with snabbdom.

**Comment by basarat** [comment]
> Named imports are definitely preferable to defaults.

@Frikki Totally agree : https://basarat.gitbooks.io/typescript/content/docs/tips/defaultIsBad.html :rose:

Was just concerned about increased length for *path* to internal only imports (notice `'typestyle/lib/es2015/something'`). Suspect that with an es2015 build `"module": "es2015",` tree shaking kicks in so one does `import {something} from "typestyle"`  instead of `import {something} from "typestyle/lib/es2015/something"` for smaller sized builds which I suspect is what you are also saying :rose: Just that I haven't tested it myself and I guess you have :heart:

---- 

@TylorS PR away please :rose:

**Comment by Frikki** [comment]
@basarat 

> ... I suspect is what you are also saying

Yes. And a :rose: to you, too. And a :heart:

**Comment by TylorS** [comment]
Wonderful, I will get on this as soon as I can :+1:. 

FWIW, I'm the author of [`motorcycle.js`](https://github.com/motorcyclejs) and a core contributor to [`most.js`](https://github.com/cujojs) (95% of my tech stack) and we provide es2015 builds for all of our packages or are updating them all as fast a we can :)

**Comment by notoriousb1t** [comment]
@TylorS would you mind doing a PR for csx and csstips for ES2015 builds?

**Comment by TylorS** [comment]
@notoriousb1t Surely, I've not used these 2 libraries, but it should effectively be the same thing. I'd be glad to assist in that.

**Comment by notoriousb1t** [comment]
We split typestyle into typestyle, csstips, and csx recently because they solve different problems.  They are all part of the typestyle project even if they are different repositories.  

- typestyle is the core
- csx provides css helpers for properties
- csstips provides mixins and things to help someone get started

**Comment by basarat** [comment]
This has been done for typestyle since `0.19.0`. Issues can be created in the other libraries and tracked there :rose:
