### ISSUE TITLE
Alternative $nest API naming

### ISSUE THREAD

**Issue by bradleyayers** [typestyle/typestyle#84]
After using typestyle for a couple of weeks and introducing it to my teams, the only hurdle I've encountered has been `$nest` and what it means.

A common stumbling block is how to translate this into typestyle:

```less
.foo {
  color: red;
  &:hover {
    color: blue;
  }
}
```

The problem with `$nest` is:

1. in the above example, it's not really thought of as "nesting", so `$nest` is immediately ignored as "not being the right approach" 
2. the `$` prefix is hard to remember

I think (1) is the important problem here — (2) could just be learned over time.

A simple fix is just changing the name to something like `$chain`, but there's probably an even better name out there.

**Comment by basarat** [comment]
* We called it $nest because : https://css-tricks.com/the-sass-ampersand/ has the first sentence `The & is an extremely useful feature in Sass (and Less). It's used when nesting` 
* Used `$` so that there is no chance of it ever conflicting with a CSS property 

Note that *something* like `$nest` is needed because in the absence of an explicitly named property allowing a string indexer turns off TypeScript strict checking. If you are curious the details are here : https://github.com/typestyle/typestyle/issues/40


> A simple fix is just changing the name to something like $chain, but there's probably an even better name out there.

Leaving as open for a week if anybody comes up with a better name.

@bradleyayers If you are okay with `$nest` *now* after hearing the rational you can close it :rose:

**Comment by basarat** [comment]
Been 12 days. I left it open longer cause of holidays but I guess we can close it now :heart:
